<a href="https://colab.research.google.com/github/Cyber-Squid1/PyTorch/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
x=torch.empty(3,3,3)
print(x)

tensor([[[ 0.0000e+00,  0.0000e+00, -6.1028e-26],
         [ 4.3910e-41,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  2.2561e-43,  0.0000e+00],
         [ 1.7797e-38,  3.1445e-41,  1.9990e-38],
         [ 3.1445e-41,  1.4013e-45,  0.0000e+00]],

        [[-1.6356e-40,  4.3911e-41,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [-1.0895e-01,  3.1444e-41, -1.0517e-01]]])


In [ ]:
randomTensor=torch.rand(2,2,2)
print(randomTensor)

tensor([[[0.0417, 0.6926],
         [0.2032, 0.6843]],

        [[0.7883, 0.9361],
         [0.4555, 0.4549]]])


In [ ]:
zeroTensor=torch.zeros(2,2,dtype=torch.int)
print(zeroTensor)
print(zeroTensor.type())
print(zeroTensor.dtype)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)
torch.IntTensor
torch.int32


In [ ]:
oneTensor=torch.ones(2,2)
print(oneTensor)
print(oneTensor.size())

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


In [ ]:
tensorFromList=torch.tensor([1,4,8,3,6,7,9,2,10])
print(tensorFromList)

tensor([ 1,  4,  8,  3,  6,  7,  9,  2, 10])


In [ ]:
t1=torch.rand(2,2)
t2=torch.rand(2,2)
# Element wise operations
print(t1+t2) # or  print(torch.add(t1,t2))
t2.add_(t1) # any function with trailing underscore (_) will do an inplace operation here t1 will be added to t2 and the result is saved in t2
print(t2)
print(t1-t2) # or print(torch.sub(t1,t2))
print(t1*t2) # or print(torch.mul(t1,t2))
print(t1/t2) # or print(torch.div(t1,t2))

print()
print()
print()
# Slicing

t3=torch.rand(5,3)
print(t3)
print(t3[:2])
print('value at position (2,2): ',t3[2,2]) # gives the value of the element at that position in a tensor
print('value at position (2,2): ',t3[2,2].item()) # gives the scalar value of the element at that position instead of a tensor like above

tensor([[0.4886, 1.0226],
        [0.7864, 1.3158]])
tensor([[0.4886, 1.0226],
        [0.7864, 1.3158]])
tensor([[-0.2967, -0.5883],
        [-0.5378, -0.5648]])
tensor([[0.0938, 0.4441],
        [0.1956, 0.9882]])
tensor([[0.3927, 0.4247],
        [0.3162, 0.5708]])



tensor([[0.0501, 0.8099, 0.0119],
        [0.6549, 0.3065, 0.7651],
        [0.0021, 0.6772, 0.3929],
        [0.4112, 0.2278, 0.9048],
        [0.2884, 0.1444, 0.3214]])
tensor([[0.0501, 0.8099, 0.0119],
        [0.6549, 0.3065, 0.7651]])
value at position (2,2):  tensor(0.3929)
value at position (2,2):  0.39291852712631226


In [ ]:
# Reshaping
a=torch.rand(5,4)
print(a) # 2D tensor
b=a.view(20)  # the number of elements must be same i.e. 5*2=10
print(b) # 1D vector
c=a.view(-1,10)  # if we do no specify the size of tensor pytorch wil automatically determine the size according to the given input
print(c)
print(c.size())

tensor([[0.0035, 0.3571, 0.0310, 0.5395],
        [0.0284, 0.8359, 0.2638, 0.9322],
        [0.6648, 0.1876, 0.5117, 0.5363],
        [0.6741, 0.5719, 0.9209, 0.8737],
        [0.1099, 0.8389, 0.8307, 0.4071]])
tensor([0.0035, 0.3571, 0.0310, 0.5395, 0.0284, 0.8359, 0.2638, 0.9322, 0.6648,
        0.1876, 0.5117, 0.5363, 0.6741, 0.5719, 0.9209, 0.8737, 0.1099, 0.8389,
        0.8307, 0.4071])
tensor([[0.0035, 0.3571, 0.0310, 0.5395, 0.0284, 0.8359, 0.2638, 0.9322, 0.6648,
         0.1876],
        [0.5117, 0.5363, 0.6741, 0.5719, 0.9209, 0.8737, 0.1099, 0.8389, 0.8307,
         0.4071]])
torch.Size([2, 10])


In [ ]:
# Torch tensor to numpy array and vice versa
a=torch.ones(5)
print(a)
b=a.numpy()
print(type(b))
print()

print()
print('Numpy to torch tensor')
a1=np.ones(6)
print(a1)
print(type(a1))
b1=torch.from_numpy(a1)
print(b1)
print(type(b1))


# Both a and b point to the same memory location so if we modify a then b will also be modified
# Same for a1 and b1
# Only happens when tensor is created on CPU and not GPU as numpy cannot handle GPU tensors
print('Both a and b point to the same memory location so if we modify a then b will also be modified')
a.add_(1)
print('a= ',a)
print('b= ',b)

a1 += 5
print('a1= ',a1)
print('b1= ',b1)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


Numpy to torch tensor
[1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
Both a and b point to the same memory location so if we modify a then b will also be modified
a=  tensor([2., 2., 2., 2., 2.])
b=  [2. 2. 2. 2. 2.]
a1=  [6. 6. 6. 6. 6. 6.]
b1=  tensor([6., 6., 6., 6., 6., 6.], dtype=torch.float64)


In [ ]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
  device=torch.device('cuda')
  x1=torch.ones(4,device=device)
  y1=torch.ones(4)
  y1=y1.to(device)
  z1=x1.to('cpu')
  print('x1= ',x1)
  print('y1= ',y1)
  print('z1= ',z1)
  print('z1 device= ',z1.device)

True
x1=  tensor([1., 1., 1., 1.], device='cuda:0')
y1=  tensor([1., 1., 1., 1.], device='cuda:0')
z1=  tensor([1., 1., 1., 1.])
z1 device=  cpu


In [ ]:
x1=torch.ones(3,3)
y1=torch.ones(3,3)
xy=torch.cat((x1,y1),1).long()
print(xy)
print(xy.type())

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])
torch.LongTensor


Gradient Calculation with Autograd

In [ ]:
x=torch.randn(3,requires_grad=True)
x

tensor([ 0.3405, -1.2869,  0.0578], requires_grad=True)

In [ ]:
y=x+2 # requires_grad=True creates a computational graph when any operation is done on that tensor
#  the result is then backpropogated for calculation of the gradient of y with respect to x this is shown by grad_fn attribute in y tensor
print(y)
z=y*y*4
z=z.mean()
print('z= ',z)
z.backward() # used to calculate dz/dx
print(x.grad)

tensor([2.3405, 0.7131, 2.0578], grad_fn=<AddBackward0>)
z=  tensor(13.6283, grad_fn=<MeanBackward0>)
tensor([6.2414, 1.9015, 5.4875])


In [ ]:
# Preventing gradient history (No back propogation)
a=torch.randn(4,requires_grad=True)
print('a= ',a)
print()

# Method 1
print('Method 1 to prevent gradient history')
a.requires_grad_(False)
print('a= ',a)
print()

# Method 2
print('Method 2 to prevent gradient history')
b=a.detach()
print('a= ',b)
print()

# Method 3
print('Method 3 to prevent gradient history')
with torch.no_grad():
  c=a*1
  print('a= ',c)

a=  tensor([-0.0457, -0.1248,  1.0614, -0.5585], requires_grad=True)

Method 1 to prevent gradient history
a=  tensor([-0.0457, -0.1248,  1.0614, -0.5585])

Method 2 to prevent gradient history
a=  tensor([-0.0457, -0.1248,  1.0614, -0.5585])

Method 3 to prevent gradient history
a=  tensor([-0.0457, -0.1248,  1.0614, -0.5585])


**Preventing gradient accumulation**

In [ ]:
# Wrong Method here gradients are accumulated
weights=torch.ones(4,requires_grad=True)

for epoch in range(3):
  model_output=(weights*3).sum()
  model_output.backward()
  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [ ]:
# Correct way, here gradients are not accumulated
weights=torch.ones(4,requires_grad=True)

for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
# DO NOT RUN THIS CELL IT WILL PRODUCE ERROR IT IS JUST FOR REPRESENTATION
# While working wth optimizers method to prevent gradient accumulation
# weights=torch.ones(4,requires_grad=True)

# optimizer=torch.optim.SGD(weights,lr=0.001)
# optimizer.step()
# optimizer.zero_grad()

**Backpropogation**

In [ ]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)

w=torch.tensor(1.0,requires_grad=True)

# Step 1: Forward Pass
y_pred=x*w
loss=(y_pred-y)**2
print(loss)

# Step 2: Backward Pass
loss.backward()
print(w.grad)

# Step 3: Update weights
# Step 4: Repeat setps 1 to 3

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


**Gradient Descent and Backpropogation in Linear Regression**

**Manually Calculating Gradients**

In [ ]:
# Here gradient and loss calculations will be done manually
# f = w*x
# w = weight=2
# X = input features
# y = actual output
X =np.array([1,2,3,4],dtype=np.float32)
Y =np.array([2,4,6,8],dtype=np.float32)

w=0.0

# model prediction
def forward(x):
    return w*x

# loss = MSE
def loss(y,y_pred):
    return ((y-y_pred)**2).mean()

# gradient calculation
# MSE= (1/n) * (w*x - y)**2 = J
# dj/dw = (1/n) *  2x(w*x - y)
def gradient(x,y,y_pred):
    return np.dot(2*x, y_pred-y).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Start training
lr=0.01
n_epochs=20

for epoch in range(n_epochs):
    # Prediction = forward pass
    y_pred=forward(X)

    # loss
    l=loss(Y,y_pred)

    # gradients
    dw =gradient(X,Y,y_pred)

    # update weights
    w -= lr*dw

    if epoch%2 == 0:
        print(f'epcoh {epoch+1}: weight = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epcoh 1: weight = 1.200, loss = 30.00000000
epcoh 3: weight = 1.872, loss = 0.76800019
epcoh 5: weight = 1.980, loss = 0.01966083
epcoh 7: weight = 1.997, loss = 0.00050331
epcoh 9: weight = 1.999, loss = 0.00001288
epcoh 11: weight = 2.000, loss = 0.00000033
epcoh 13: weight = 2.000, loss = 0.00000001
epcoh 15: weight = 2.000, loss = 0.00000000
epcoh 17: weight = 2.000, loss = 0.00000000
epcoh 19: weight = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


**Automatic Gradient Calculation Using autograd()**

In [ ]:
# Here gradient and loss calculations will be done manually
# f = w*x
# w = weight=2
# X = input features
# y = actual output
X =torch.tensor([1,2,3,4],dtype=torch.float32)
Y =torch.tensor([2,4,6,8],dtype=torch.float32)

w=torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

# model prediction
def forward(x):
    return w*x

# loss = MSE
def loss(y,y_pred):
    return ((y-y_pred)**2).mean()

print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Start training
lr=0.01
n_epochs=100

for epoch in range(n_epochs):
    # Prediction = forward pass
    y_pred=forward(X)

    # loss
    l=loss(Y,y_pred)

    # gradients = backward pass
    l.backward()

    # update weights
    with torch.no_grad():
        w -= lr*w.grad

    # zore_grad
    w.grad.zero_()

    if epoch%10 == 0:
        print(f'epcoh {epoch+1}: weight = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epcoh 1: weight = 0.300, loss = 30.00000000
epcoh 11: weight = 1.665, loss = 1.16278565
epcoh 21: weight = 1.934, loss = 0.04506890
epcoh 31: weight = 1.987, loss = 0.00174685
epcoh 41: weight = 1.997, loss = 0.00006770
epcoh 51: weight = 1.999, loss = 0.00000262
epcoh 61: weight = 2.000, loss = 0.00000010
epcoh 71: weight = 2.000, loss = 0.00000000
epcoh 81: weight = 2.000, loss = 0.00000000
epcoh 91: weight = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


Automating Training Pipeline in PyTorch using inbuilt functions

Step 1: Design Model(input_size,output_size,forward_pass)

Step 2: Construct Loss and Optimizer

Step 3: Training Loop (

        - forward pass: compute prediction
        - backward pass/propogation: gradients
        - update weights
)

In [ ]:
import torch.nn as nn

In [ ]:
X =torch.tensor([1,2,3,4],dtype=torch.float32)
Y =torch.tensor([2,4,6,8],dtype=torch.float32)

w=torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

# model prediction
def forward(x):
    return w*x


print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Start training
lr=0.01
n_epochs=100
loss=nn.MSELoss()
optimizer=torch.optim.SGD([w],lr=lr)


for epoch in range(n_epochs):
    # Prediction = forward pass
    y_pred=forward(X)

    # loss
    l=loss(Y,y_pred)

    # gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()

    # zore_grad
    optimizer.zero_grad()

    if epoch%10 == 0:
        print(f'epcoh {epoch+1}: weight = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epcoh 1: weight = 0.300, loss = 30.00000000
epcoh 11: weight = 1.665, loss = 1.16278565
epcoh 21: weight = 1.934, loss = 0.04506890
epcoh 31: weight = 1.987, loss = 0.00174685
epcoh 41: weight = 1.997, loss = 0.00006770
epcoh 51: weight = 1.999, loss = 0.00000262
epcoh 61: weight = 2.000, loss = 0.00000010
epcoh 71: weight = 2.000, loss = 0.00000000
epcoh 81: weight = 2.000, loss = 0.00000000
epcoh 91: weight = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


In [ ]:
X =torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)
Y =torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)
X_test=torch.tensor([5],dtype=torch.float32)

n_samples,n_features=X.shape
print(n_samples,n_features)

input_size=n_features
output_size=n_features
# model=nn.Linear(input_size,output_size)

class LinearRegression(nn.Module):
    def __init__ (self,input_dim,output_dim):
        super(LinearRegression,self).__init__()

        # define layers
        self.lin1=nn.Linear(input_dim, output_dim)

    def forward(self,x):
        return self.lin1(x)

model=LinearRegression(input_size,output_size)

# model prediction

print(f'Prediction before training: f(5) = {model(X_test).item():.3f}')

# Start training
lr=0.01
n_epochs=100
loss=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(), lr=lr)


for epoch in range(n_epochs):
    # Prediction = forward pass
    y_pred=model(X)

    # loss
    l=loss(Y,y_pred)

    # gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()

    # zore_grad
    optimizer.zero_grad()

    if epoch%10 == 0:
        [w,b] =model .parameters()
        print(f'epcoh {epoch+1}: weight = {w[0][0].item():.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')

4 1
Prediction before training: f(5) = -1.742
epcoh 1: weight = 0.187, loss = 45.48641968
epcoh 11: weight = 1.731, loss = 1.17788172
epcoh 21: weight = 1.979, loss = 0.03145315
epcoh 31: weight = 2.018, loss = 0.00173527
epcoh 41: weight = 2.024, loss = 0.00091274
epcoh 51: weight = 2.024, loss = 0.00084095
epcoh 61: weight = 2.023, loss = 0.00079152
epcoh 71: weight = 2.023, loss = 0.00074543
epcoh 81: weight = 2.022, loss = 0.00070204
epcoh 91: weight = 2.021, loss = 0.00066118
Prediction after training: f(5) = 10.043
